// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package main

type ChallengeResponse struct {
	UserID   string `json:"userId"`
	Question string `json:"question"`
	Answer   string `json:"answer"`
	Rating   string `json:"rating"`
	Insight  string `json:"insight"`
}

type Mutation struct {
}

type Problem struct {
	ID         string   `json:"id"`
	Question   string   `json:"question"`
	Categories []string `json:"categories"`
	Type       string   `json:"type"`
}

type ProblemInput struct {
	Question   string   `json:"question"`
	Categories []string `json:"categories"`
	Type       string   `json:"type"`
}

type Query struct {
}

type User struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

type UserInput struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}
