// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type ChallengeResponse struct {
	UserID   string `json:"userId"`
	Question string `json:"question"`
	Answer   string `json:"answer"`
	Rating   string `json:"rating"`
	Insight  string `json:"insight"`
}

type Mutation struct {
}

type Problem struct {
	ID         string   `json:"id"`
	Question   string   `json:"question"`
	Categories []string `json:"categories"`
	Type       string   `json:"type"`
}

type ProblemInput struct {
	Question   string   `json:"question"`
	Categories []string `json:"categories"`
	Type       string   `json:"type"`
}

type Query struct {
}

type Topic struct {
	Name string `json:"name"`
}

type User struct {
	ID       string   `json:"id"`
	Name     string   `json:"name"`
	Email    string   `json:"email"`
	Password string   `json:"password"`
	Topics   []string `json:"topics,omitempty"`
}

type UserInput struct {
	ID       string `json:"_id"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
