name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'src/frontend/**'

jobs:
  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash

      - name: Build frontend
        run: |
          cd src/frontend
          bun run build

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2 # Adjust region as needed

      - name: Sync with S3
        run: |
          aws s3 sync ./src/frontend/dist s3://qriosity-site --delete

      - name: Confirm Deployment
        run: echo "Deployment to S3 bucket qriosity-site completed successfully."